version: '3.9'

services:
  mysqldb:
    image: mysql:8.0.33
    container_name: MysqlServer
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=test
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
    ports:
      - 3308:3306
    volumes:
      - ./db:/var/lib/mysql
    tty: true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysqldb", "-uuser", "-ppass"]
      interval: 5s  # Check the health status every 5 seconds
      timeout: 10s  # Consider the health check failed after 10 seconds
      retries: 5  # Allow up to 5 retries before marking the service as unhealthy

  # fastapi_app:
  #   build: .
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
  #   volumes:
  #     - .:/usr/src/app
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mysqldb
  #   environment:
  #     - DATABASE_URL=mysql+pymysql://admin:123@mysqldb:3306/test
